version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    ports:
    - "5432:5432"

