version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    ports:
    - "5420:5432" # Port 5432 might be used by other things on your PC, so it's been remapped to 5420

